export const biologyFacts = [
    { id: 1, title: "The Double Helix", description: "DNA forms a double helix shape, first discovered by Watson, Crick, and Franklin in 1953.", category: "Genetics" },
    { id: 2, title: "Base Pairs", description: "Adenine pairs with Thymine (A-T), and Cytosine pairs with Guanine (C-G) in DNA sequences.", category: "Molecular Biology" },
    { id: 3, title: "Mitochondria", description: "Often called the powerhouse of the cell, it generates most of the cell's supply of ATP.", category: "Cytology" },
    { id: 4, title: "Ribosomes", description: "The protein builders or the protein synthesizers of the cell.", category: "Cytology" },
    { id: 5, title: "Nucleus", description: "The control center of the cell, containing the majority of the cell's genetic material.", category: "Cytology" },
    { id: 6, title: "Enzymes", description: "Biological catalysts that significantly speed up the rate of virtually all chemical reactions within cells.", category: "Biochemistry" },
    { id: 7, title: "Photosynthesis", description: "The process by which green plants use sunlight to synthesize nutrients from carbon dioxide and water.", category: "Botany" },
    { id: 8, title: "Chloroplasts", description: "Organelles found in plant cells that conduct photosynthesis.", category: "Botany" },
    { id: 9, title: "Neurons", description: "Cells within the nervous system that transmit information to other nerve cells, muscle, or gland cells.", category: "Anatomy" },
    { id: 10, title: "Synapse", description: "The tiny gap between two neurons where neurotransmitters are released to communicate signals.", category: "Neurobiology" },
    { id: 11, title: "Red Blood Cells", description: "Also known as erythrocytes, they lack a nucleus and are filled with hemoglobin to carry oxygen.", category: "Histology" },
    { id: 12, title: "White Blood Cells", description: "Cells of the immune system that are involved in protecting the body against infectious disease.", category: "Immunology" },
    { id: 13, title: "Antibodies", description: "Proteins produced by the immune system to neutralize pathogens such as pathogenic bacteria and viruses.", category: "Immunology" },
    { id: 14, title: "Evolution", description: "The change in the heritable characteristics of biological populations over successive generations.", category: "Evolutionary Biology" },
    { id: 15, title: "Natural Selection", description: "The differential survival and reproduction of individuals due to differences in phenotype.", category: "Evolutionary Biology" },
    { id: 16, title: "Meiosis", description: "A special type of cell division that reduces the chromosome number by half, creating four haploid cells.", category: "Genetics" },
    { id: 17, title: "Mitosis", description: "A part of the cell cycle when replicated chromosomes are separated into two new nuclei.", category: "Cell Biology" },
    { id: 18, title: "RNA", description: "Ribonucleic acid acts as a messenger carrying instructions from DNA for controlling the synthesis of proteins.", category: "Genetics" },
    { id: 19, title: "Transcription", description: "The first step of gene expression where a particular segment of DNA is copied into RNA.", category: "Genetics" },
    { id: 20, title: "Translation", description: "The process in which ribosomes in the cytoplasm synthesize proteins after transcription.", category: "Biochemistry" },
    { id: 21, title: "Homeostasis", description: "The state of steady internal, physical, and chemical conditions maintained by living systems.", category: "Physiology" },
    { id: 22, title: "Endoplasmic Reticulum", description: "A continuous membrane system that forms a series of flattened sacs, responsible for protein synthesis and transport.", category: "Cytology" },
    { id: 23, title: "Golgi Apparatus", description: "Packages proteins into membrane-bound vesicles inside the cell before the vesicles are sent to their destination.", category: "Cytology" },
    { id: 24, title: "Stem Cells", description: "Cells with the potential to develop into many different types of cells in the body.", category: "Developmental Biology" },
    { id: 25, title: "Viruses", description: "An infectious microbe consisting of a segment of nucleic acid surrounded by a protein coat.", category: "Virology" },
    { id: 26, title: "Bacteria", description: "Ubiquitous, mostly free-living organisms often consisting of one biological cell.", category: "Microbiology" },
    { id: 27, title: "Fungi", description: "Any member of the group of eukaryotic organisms that includes microorganisms such as yeasts and molds.", category: "Mycology" },
    { id: 28, title: "Taxonomy", description: "The science of naming, defining and classifying groups of biological organisms on the basis of shared characteristics.", category: "Biology" },
    { id: 29, title: "Ecosystems", description: "A community of living organisms in conjunction with the nonliving components of their environment.", category: "Ecology" },
    { id: 30, title: "CRISPR", description: "A family of DNA sequences found in the genomes of prokaryotic organisms such as bacteria, used for gene editing.", category: "Biotechnology" }
];
